// components/home/Hero.vue
<script setup lang="ts">
const { t } = useAppI18n()
</script>

<template>
  <section class="hero">
    <div class="hero-content">
      <h1>Ihre Sicherheit ist unsere <span>Verantwortung</span></h1>
      <p>{{ t('home.heroSubtitle') }}</p>
      <NuxtLink to="/contact" class="cta-button">
        {{ t('home.contactBtn') }}
      </NuxtLink>
    </div>
  </section>
</template>

// src/components/home/Hero.jsx
import { useTranslation } from 'react-i18next';
import { Link } from 'react-router-dom';
import './Hero.css';

const Hero = () => {
  const { t } = useTranslation();

  return (
    <section className="hero">
      <div className="hero-content">
        <h1>Ihre Sicherheit ist unsere <span>Verantwortung</span></h1>
        <p>{t('home.heroSubtitle')}</p>
        <Link to="/contact" className="cta-button">
          {t('home.contactBtn')}
        </Link>
      </div>
    </section>
  );
};

export default Hero;
